import os
import sys
from fpdf import FPDF

class ProjectDocPDF(FPDF):
    def header(self):
        # Only show header on page 2 and onwards
        if self.page_no() > 1:
            self.set_font("Arial", "I", 8)
            self.set_text_color(100, 116, 139) # slate gray (RGB 100, 116, 139)
            self.cell(0, 8, "RideShare Platform (Uber Clone) - Capstone Project Documentation", 0, 0, "L")
            self.cell(0, 8, "July 2026", 0, 1, "R")
            self.set_draw_color(226, 232, 240) # Slate 200
            self.set_line_width(0.5)
            self.line(15, 18, 195, 18)
            self.ln(6)

    def footer(self):
        self.set_y(-15)
        self.set_font("Arial", "I", 8)
        self.set_text_color(100, 116, 139)
        # Total page count alias is handled via {nb}
        self.cell(0, 10, f"Page {self.page_no()} of {{nb}}", 0, 0, "C")

    def create_title_page(self):
        self.add_page()
        
        # Upper decorative band
        self.set_fill_color(30, 41, 59) # Slate 800
        self.rect(0, 0, 210, 105, "F")
        
        # Royal blue accent strip
        self.set_fill_color(37, 99, 235) # Blue 600
        self.rect(0, 105, 210, 6, "F")
        
        # Title inside upper band
        self.set_y(35)
        self.set_font("Arial", "B", 28)
        self.set_text_color(255, 255, 255)
        self.cell(0, 12, "RIDESHARE PLATFORM", 0, 1, "C")
        
        self.set_font("Arial", "", 15)
        self.set_text_color(191, 219, 254) # Blue 200
        self.cell(0, 10, "Capstone Project Documentation & Technical Guide", 0, 1, "C")
        
        # Main Subtitle and Description in the lower portion
        self.set_y(130)
        self.set_font("Arial", "B", 18)
        self.set_text_color(30, 41, 59) # Slate 800
        self.cell(0, 10, "System Architecture & Backend Logic", 0, 1, "C")
        
        # Divider line
        self.set_draw_color(37, 99, 235) # Blue 600
        self.set_line_width(1)
        self.line(45, 145, 165, 145)
        
        self.set_y(160)
        self.set_font("Arial", "", 11)
        self.set_text_color(71, 85, 105) # Slate 600
        desc = (
            "A comprehensive overview of a complete, dual-facing ridesharing solution "
            "(similar to Uber or Lyft). This system features a real-time NodeJS backend, "
            "interactive maps for ride matching and tracking, and dedicated front-end applications "
            "for both riders and drivers.\n\n"
            "This document is written in clear, simple language to explain the code structure, "
            "used packages, database schemas, and the real-time workflows that connect users."
        )
        self.multi_cell(0, 6.5, desc, 0, "C")
        
        # Metadata block at the bottom
        self.set_y(245)
        self.set_font("Arial", "B", 10.5)
        self.set_text_color(30, 41, 59)
        self.cell(0, 5.5, "Date: July 3, 2026", 0, 1, "C")
        self.set_font("Arial", "", 10.5)
        self.set_text_color(100, 116, 139)
        self.cell(0, 5, "Prepared for: Capstone Project Submission", 0, 1, "C")
        self.cell(0, 5, "Generated by: Antigravity AI Coding Assistant", 0, 1, "C")

    def add_chapter(self, title):
        self.set_font("Arial", "B", 16)
        self.set_text_color(30, 41, 59) # Slate 800
        self.cell(0, 10, title, 0, 1, "L")
        self.set_draw_color(37, 99, 235) # Blue 600
        self.set_line_width(0.75)
        self.line(15, self.get_y(), 195, self.get_y())
        self.ln(5)

    def add_section(self, title):
        self.set_font("Arial", "B", 12.5)
        self.set_text_color(37, 99, 235) # Blue 600
        self.cell(0, 8, title, 0, 1, "L")
        self.ln(2)

    def add_body_text(self, text):
        self.set_font("Arial", "", 10)
        self.set_text_color(51, 65, 85) # Slate 700
        self.multi_cell(0, 5.5, text)
        self.ln(3)

    def add_bullet(self, title, desc):
        self.set_font("Arial", "B", 10)
        self.set_text_color(30, 41, 59)
        self.write(5.5, " *  ")
        self.write(5.5, title + ": ")
        self.set_font("Arial", "", 10)
        self.set_text_color(51, 65, 85)
        self.write(5.5, desc + "\n")
        self.ln(1)

    def add_code_block(self, title, code_text):
        self.set_font("Arial", "B", 9)
        self.set_text_color(71, 85, 105)
        self.cell(0, 5, "   [Schema Snippet] " + title, 0, 1, "L")
        
        self.set_fill_color(248, 250, 252) # Slate 50
        self.set_draw_color(226, 232, 240) # Slate 200
        self.set_font("Courier", "", 8.5)
        self.set_text_color(51, 65, 85)
        
        # We output using multi_cell with borders and backgrounds
        self.multi_cell(0, 4.5, code_text, 1, "L", fill=True)
        self.ln(3)

def generate_project_pdf(output_path):
    pdf = ProjectDocPDF()
    pdf.alias_nb_pages() # Set total pages
    pdf.set_margins(15, 20, 15)
    
    # 1. Cover Page
    pdf.create_title_page()
    
    # 2. Project Overview Page
    pdf.add_page()
    pdf.add_chapter("1. Project Architecture & Overview")
    
    overview_text = (
        "This project is an end-to-end RideSharing Application (an Uber/Lyft clone) built to demonstrate "
        "modern full-stack web development. The project is split into three main parts: a centralized "
        "Backend API Server and two distinct Frontend Web Applications for Riders and Drivers. This split "
        "allows both user roles to have tailored user interfaces and clean, non-interfering workflows."
    )
    pdf.add_body_text(overview_text)
    
    pdf.add_section("The Three Main Applications")
    
    pdf.add_bullet("1. Backend Server", 
                   "A NodeJS & Express server that manages database operations, secures accounts, performs "
                   "ride calculations, and handles real-time synchronization between clients using WebSockets.")
    pdf.add_bullet("2. Rider Client App", 
                   "A React-based web dashboard where riders log in, view live maps, enter pickup and dropoff destinations, "
                   "request rides, review the calculated fare and distance, track their driver's car marker, and rate completed trips.")
    pdf.add_bullet("3. Driver Client App", 
                   "A React-based web dashboard where drivers toggling availability see a stream of nearby ride requests, "
                   "accept them, update the progress of active rides (arrived, in-progress, completed), view location markers, "
                   "and monitor their dashboard stats (total rides, rating, and earnings).")
    
    pdf.ln(4)
    pdf.add_section("Key Features of the System")
    pdf.add_bullet("Real-Time Tracking", "Sockets broadcast GPS coordinates instantly between driver and rider maps.")
    pdf.add_bullet("Dynamic Fare Calculation", "Automated distance calculation and fare estimation based on destination coordinates.")
    pdf.add_bullet("Secure Auth", "Password encryption on signup, with role-based JWT validation for drivers and riders.")
    pdf.add_bullet("Interactive Mapping", "Uses OpenStreetMap layers with Leaflet to select and track locations visually.")
    
    # 3. Packages Used Page
    pdf.add_page()
    pdf.add_chapter("2. Package Manifest (Packages Used)")
    
    pkg_intro = (
        "Each application in the workspace contains its own package.json. The packages listed below were chosen "
        "to satisfy security, validation, real-time communications, database mapping, and mapping visualization needs."
    )
    pdf.add_body_text(pkg_intro)
    
    pdf.add_section("A. Backend Server Packages")
    pdf.add_bullet("express", "The minimalist web framework used to configure and run the REST API endpoints.")
    pdf.add_bullet("mongoose", "An Object Data Modeling (ODM) library for MongoDB. It enforces strict schemas and simplifies database queries.")
    pdf.add_bullet("socket.io", "Enables real-time, bi-directional communication. Used to send ride alerts and live locations.")
    pdf.add_bullet("bcryptjs", "A cryptographic package used to hash and salt passwords, protecting user data in database storage.")
    pdf.add_bullet("jsonwebtoken (jwt)", "Signs and verifies JSON Web Tokens to establish secure, stateless sessions for users.")
    pdf.add_bullet("cors", "Enables Cross-Origin Resource Sharing. Allows frontend apps running on ports 5173/5174 to call the API server.")
    pdf.add_bullet("dotenv", "Loads environment configuration variables from a local `.env` file (e.g. database connection string, port, secrets).")
    pdf.add_bullet("express-validator", "A validation middleware. It blocks invalid payloads (like short passwords or malformed email strings) before they hit database queries.")
    pdf.add_bullet("nodemon (dev)", "Restarts the server processes automatically on file updates, speeding up developer productivity.")
    
    pdf.ln(3)
    pdf.add_section("B. Frontend Applications Packages (Rider & Driver Apps)")
    pdf.add_bullet("react & react-dom", "The building block libraries for constructing reactive, modular user interfaces.")
    pdf.add_bullet("react-router-dom", "Handles URL navigation and private route protection (blocking unauthorized users from home screens).")
    pdf.add_bullet("axios", "A clean, promise-based HTTP library used to submit login forms, fetch ride history, and trigger api updates.")
    pdf.add_bullet("leaflet", "The industry-standard open-source map engine that does the heavy-lifting of rendering geographical maps.")
    pdf.add_bullet("react-leaflet", "A set of wrapper bindings that allow Leaflet maps to be integrated as React components (e.g. <MapContainer>, <Marker>).")
    pdf.add_bullet("socket.io-client", "Connects the client app to the server sockets. Listens for live coordinates and statuses.")
    pdf.add_bullet("vite (dev)", "The lighting-fast build bundler that runs the frontend apps locally during development.")
    
    # 4. Database Models Page
    pdf.add_page()
    pdf.add_chapter("3. Database Structure & Schemas")
    
    db_intro = (
        "The project uses MongoDB as its database, which is a document-oriented database. "
        "Through Mongoose, we enforce schemas on the tables (collections) to structure relations. "
        "Below are the structures for the three core schemas in the system."
    )
    pdf.add_body_text(db_intro)
    
    # User Model
    user_schema_code = (
        "UserSchema = {\n"
        "  username:  { type: String, required: true, unique: true },\n"
        "  password:  { type: String, required: true },  // stored as bcrypt hash\n"
        "  role:      { type: String, enum: ['rider', 'driver'], default: 'rider' }\n"
        "}"
    )
    pdf.add_code_block("User Model - Defines account credentials and identity.", user_schema_code)
    
    # Driver Model
    driver_schema_code = (
        "DriverSchema = {\n"
        "  user:          { type: ObjectId, ref: 'User', unique: true },\n"
        "  vehicleInfo:   { make, model, plate, color },\n"
        "  location:      { lat: Number, lng: Number },  // live GPS coordinate\n"
        "  isAvailable:   { type: Boolean, default: false },\n"
        "  rating:        { type: Number, default: 5.0 },\n"
        "  totalRides:    { type: Number, default: 0 },\n"
        "  totalEarnings: { type: Number, default: 0 }\n"
        "}"
    )
    pdf.add_code_block("Driver Model - Extends User info with vehicle state and earnings.", driver_schema_code)
    
    # Ride Model
    ride_schema_code = (
        "RideSchema = {\n"
        "  rider:       { type: ObjectId, ref: 'User', required: true },\n"
        "  driver:      { type: ObjectId, ref: 'Driver', default: null },\n"
        "  pickup:      { address: String, lat: Number, lng: Number },\n"
        "  dropoff:     { address: String, lat: Number, lng: Number },\n"
        "  status:      { type: String, enum: ['pending', 'accepted', 'in_progress', 'completed', 'cancelled'] },\n"
        "  fare:        Number,\n"
        "  distance:    Number, // calculated in km\n"
        "  riderRating: Number  // feedback rating from 1 to 5\n"
        "}"
    )
    pdf.add_code_block("Ride Model - Tracks the journey, transactions, and state changes.", ride_schema_code)
    
    # 5. Backend Logic Page
    pdf.add_page()
    pdf.add_chapter("4. How the Backend Works (Logic & Flow)")
    
    backend_intro = (
        "Here is the step-by-step description of how the backend handles authentication, ride bookings, "
        "real-time GPS synchronization, and transactions in simple words."
    )
    pdf.add_body_text(backend_intro)
    
    pdf.add_section("A. Registration & Authentication Flow")
    auth_flow = (
        "When a user signs up, the backend accepts their username and password. It runs validation checks, "
        "hashes the password using the bcryptjs library (so password strings are never saved in plain text), "
        "and creates a User document. For drivers, it also creates an empty Driver document to track vehicle information.\n"
        "When logging in, the server checks the username, compares the password hash, and signs a JSON Web Token (JWT). "
        "This token contains the user's ID, username, and role. The client stores this token in localStorage. "
        "For any protected action, the client sends this token in its headers. The backend auth middleware intercepts the "
        "request, decrypts the token, checks the role, and allows or blocks the request."
    )
    pdf.add_body_text(auth_flow)
    
    pdf.add_section("B. Ride Creation & Fare Calculation")
    ride_calc = (
        "When a Rider selects a pickup and dropoff location on the map, the Rider app sends the coordinate pairs "
        "to the backend. The backend uses the Haversine Formula (a mathematical equation that calculates "
        "the great-circle distance between two points on a sphere using latitude and longitude) to calculate the distance "
        "in kilometers. It then calculates the fare using a simple formula: a base price of $2.50, plus $1.20 per kilometer.\n"
        "The server creates a new Ride record with status 'pending'. It then broadcasts a message via WebSockets "
        "('ride:new_request') to all active drivers connected to the platform. This makes the request pop up instantly "
        "on the dashboards of nearby drivers."
    )
    pdf.add_body_text(ride_calc)
    
    # 6. Backend Logic Page 2
    pdf.add_page()
    pdf.add_chapter("5. Live Synchronization & Ride Completion")
    
    pdf.add_section("C. Acceptance & WebSocket Rooms")
    sockets_flow = (
        "When a driver accepts a pending ride, the driver's client sends a PATCH request to the backend. The backend "
        "checks if the ride is still pending. If yes, it links the driver's ID to the ride and updates the status to 'accepted'.\n"
        "To update clients without spamming everyone, the backend uses Socket.IO 'Rooms':\n"
        "  - Upon logging in, every user joins a room named '<role>:<userId>' (e.g. 'rider:60b784a9...').\n"
        "  - The server emits a 'ride:status_update' event targeting only the rider's personal room. "
        "The Rider app hears this update and immediately redraws the UI, showing driver name and car details.\n"
        "  - The server also emits a global 'ride:accepted' event to all other drivers so the ride disappears from their queue."
    )
    pdf.add_body_text(sockets_flow)
    
    pdf.add_section("D. Live Tracking (GPS Updates)")
    gps_tracking = (
        "Once a ride is active, the driver's app uses browser location APIs to fetch their GPS coordinates and sends them "
        "to the socket server via 'driver:location_update'.\n"
        "The socket server receives the coordinates, saves them to the Driver's document, and broadcasts them. "
        "It emits 'ride:<rideId>:driver_location' which is listened to only by the specific rider tracking that ride. "
        "This allows the rider's map marker to smoothly glide along the map roads in real-time."
    )
    pdf.add_body_text(gps_tracking)
    
    pdf.add_section("E. Completion, Earnings & Ratings")
    completion_flow = (
        "When the driver reaches the destination, they press 'Complete Trip' in their app. "
        "The backend: \n"
        "  1. Updates the Ride document status to 'completed' and sets the completion timestamp.\n"
        "  2. Adds the calculated fare to the driver's 'totalEarnings' database field and increments their 'totalRides' count.\n"
        "  3. Sends a socket update to the rider telling them the ride is completed.\n"
        "Upon receiving this, the rider app shows a rating screen. When the rider submits a rating (1-5 stars), the backend "
        "re-calculates the driver's average rating using a weighted formula: \n"
        "New Rating = ((Old Average * Previous Ride Count) + New Rating Value) / (Ride Count + 1).\n"
        "This keeps ratings accurate and prevents recent ratings from distorting historical scores."
    )
    pdf.add_body_text(completion_flow)
    
    pdf.ln(5)
    # Highlight block
    pdf.set_fill_color(239, 246, 255) # light blue
    pdf.set_draw_color(191, 219, 254) # blue border
    pdf.set_font("Arial", "I", 10)
    pdf.set_text_color(29, 78, 216) # dark blue text
    highlight_text = (
        "Summary: This architecture utilizes REST API endpoints for non-realtime state changes (logins, requests, completion) "
        "and WebSockets (Socket.IO) for high-frequency updates (GPS, ride requests, cancellations), establishing a highly "
        "performant, scalable, and responsive application."
    )
    pdf.multi_cell(0, 6, highlight_text, 1, "C", fill=True)

    # Save to file
    pdf.output(output_path)
    print(f"PDF generated successfully at: {output_path}")

if __name__ == "__main__":
    out = "c:\\Users\\VERSH\\OneDrive\\Desktop\\capstone\\project_documentation.pdf"
    if len(sys.argv) > 1:
        out = sys.argv[1]
    generate_project_pdf(out)
